apiVersion: v1
kind: Service
metadata:
  name: web-app-backend
  namespace: backend
spec:
  type: LoadBalancer
  loadBalancerIP: 34.148.104.110
  selector:
    app: web-app-backend
  ports:
    - port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-frontend
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: web-app-frontend
  ports:
    - port: 8080
      targetPort: 8080
