apiVersion: v1
kind: Service
metadata:
  name: web-app-frontend
  namespace: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: web-app-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 8080
