apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-frontend
  namespace: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: web-app-frontend
  template:
    metadata:
      labels:
        app: web-app-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: BACKEND_URL
              value: {{ .Values.frontend.backendURL }}
          ports:
            - containerPort: 8080
